[package]
name = "a-stock-backtester"
version = "1.5.2"
description = "A-share historical backtester"
edition = "2021"

[lib]
name = "a_stock_backtester_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tauri = { version = "2", features = [] }
tauri-plugin-process = "2.3.1"
tauri-plugin-updater = "2.10.1"
url = "2.5.8"
fs2 = "0.4"
reqwest = { version = "0.13.3", default-features = false }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
